### ISSUE TITLE
__init__.py

### ISSUE THREAD

**Issue by CoolNamesAllTaken** [Manwholikespie/thesaurus#4]
Thanks for making this API!  It's a fantastic resource.  I was recently trying to use this as a submodule on a project but was having trouble using it without an __init__.py file (the thesaurus-api folder wasn't being recognized as a python module, making it hard for me to import it from another folder).  Is there any chance that an __init__.py empty python file could be added to the project directory?

**Comment by Manwholikespie** [comment]
Hmm. And thus a potential flaw was discovered. I designed it all in one file so that you could just have the `thesaurus.py` file in your code, and not worry about the whole folder, but I can see why you would want to have it in there like that. I saw a few other people doing that, but I wasn't quite sure what their `.gitmodules` were for so I kinda just ignored it.

The main problem I foresee is user confusion. The project is named with a dash: *thesaurus-api*, yet the primary file is *thesaurus.py*, and if you were to import from a folder it would be *thesaurus_api*. I'm in the middle of finals right now and all the nice stuff that entails, so I'll have to get back to you on this. I definitely like your ideas to make it more accessible though. I'm just kinda sitting here wishing I didn't use a dash.

In the meantime, it's as simple as `__init__.py` saying `from .thesaurus import *` and you doing `from thesaurus_api import Word` in your code.

**Comment by CoolNamesAllTaken** [comment]
Hah, I'm in the middle of finals right now too.  I'm actually using your thesaurus scraping function as part of an AI final project (Thesaurus.com has wayyy more synonyms than NLTK wordnet).

I tried importing as a git submodule named thesaurus_api, but was having issues with adding a __init__.py file and having it work on my teammates' computers (they'd all have to add the init file manually and deal with the git weirdness accordingly).  I ended up downloading the .zip and throwing it into its own folder called thesaurus_api, no submodules and no weirdness involved.

If the folder was renamed to thesaurus_api and the init file was added, I think all would be well :)

Also, possible idea for future expansion: there's hella words on each thesaurus.com page in the "also related to XXX" category.  Scraping those would open up a lot of new doors for word association.

Good luck on finals!

**Comment by syelluru** [comment]
Hi Coolnamesalltaken!

I faced this issue, but I fixed it by appending the path to the python path.

Example:

import sys
sys.path.append('/Users/SuhasYelluru/anaconda/envs/py27/lib/python2.7/site-packages/thesaurus-api')

**Comment by Manwholikespie** [comment]
We're now on pypi! 🎊 😄 🥂 The repo has also been renamed so there's no slash.
To install, all you have to do now is: `$ pip install thesaurus`

Thanks for your help.

**Comment by CoolNamesAllTaken** [comment]
Congratulations, and thanks for the great resource!
