### ISSUE TITLE
Add version tag and setup.py

### ISSUE THREAD

**Issue by rahilwazir** [Manwholikespie/thesaurus#7]
Please push a stable tag i.e `0.1` and `setup.py` for easy install. Using my fork version https://github.com/rahilwazir/thesaurus-api. Let me know if PR is needed.

**Comment by Manwholikespie** [comment]
This is awesome! Thanks for your help. To be honest, I have no idea how packaging works, and while it doesn't look there will be any conflicts, I want to research it a bit before merging.

Also, I plan on renaming this repo sometime soon so that there are fewer problems when importing (due to the dash), so I'll probably hold off on packaging until I've decided on a final name. I'll merge it ASAP once I've done that.

Thanks again!
